language: csharp
solution: Cottle.sln

matrix:
  include:
    - os: linux
      dist: trusty
      dotnet: 1.0.0-preview2-003121
      mono: latest
      env: DOTNETCORE=1

install:
  - nuget restore Cottle.sln
  - nuget install NUnit.Console -Version 3.0.1 -OutputDirectory tests

script:
  - xbuild /p:Configuration=Release Cottle.sln
  - mono ./tests/NUnit.Console.3.0.1/tools/nunit3-console.exe ./Cottle.Test/bin/Release/Cottle.Test.dll
# - nuget pack -Prop Configuration=Release -Prop Platform=AnyCPU ./Cottle/Cottle.csproj
  - rm -fr ./artifacts
  - dotnet restore
  - dotnet test ./Cottle.Test -c Release -f netcoreapp1.0
  - dotnet pack ./Cottle -c Release -o ./artifacts
