name: build

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    strategy:
      matrix:
        dotnet: # https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json
          - version: 3.1.x
            framework_app: netcoreapp3.1
            framework_dll: netstandard2.0
    name: Build & Test Cottle with .NET v${{ matrix.dotnet.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet.version }}
      - run: dotnet restore src
      - run: dotnet build src/Cottle -f ${{ matrix.dotnet.framework_dll }}
      - run: dotnet test src/Cottle.Test -f ${{ matrix.dotnet.framework_app }}
